### ISSUE TITLE
can make config file ?

### ISSUE THREAD

**Issue by K3IDB** [apoiat/Esx_Deliveries#3]
i dont know how to config
what's file name ?

**Comment by apoiat** [comment]
It's a C# plugin so you can't really configure it as you would with a lua script. Easy configuration is provided through the available convars. If you want to customize it further you'll have to download the source code, modify it and build back the plugin yourself. Most stuff are located at DeliveryData.cs
Proceed with caution

**Comment by K3IDB** [comment]
can you tell me about "How to build Client File" ?
i try to config but its not work :'(
