### ISSUE TITLE
Icon appearing on Minimap

### ISSUE THREAD

**Issue by robwhitewick** [apoiat/Esx_Deliveries#4]
Hi there,

It seems that I cannot recompile whilst retaining the updated features? When I update to the release you have provided the deposits are taken the same with the payments, but as soon as I compile the code into a dll as you say to do it no longer works. It doesn't give me any money (it's like the server events are not triggering at all).

Many thanks :)

**Comment by apoiat** [comment]
You are probably not implementing the server script provided with the repo. It's imporant in order to work with esx paymers. The server side code is in lua.

**Comment by robwhitewick** [comment]
I loaded the server.lua alongside it. I'll try again today I guess.
Also your icon is displayed no matter where you are. You can fix this by using setblipdisplay I think 3 removes it from the minimap but it stays on the map.

Also when I loaded the dll I made it didn't have the updated you have added such as going back and finishing the mission. Not sure what I did wrong there. Sorry for all the questions!

**Comment by apoiat** [comment]
Hey there, any updates?

**Comment by robwhitewick** [comment]
Still the same issue. Not sure what im doing wrong really! Is it possible that you uploaded the wrong source code? (More likely that im just a dumbass).

**Comment by robwhitewick** [comment]
Right fixed it. Moving the main.lua from the server folder into the main resource folder magicly fixed it. (you obviously have to change the resource.lua aswell
